config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  devise_for :admin_users

  namespace :admin do
    get "authors/index"
    get "/" => "dashboards#index"
    resources :articles do
      member do
        delete :destroy_cover_image
      end
    end
    resources :categories do
      member do
        delete :destroy_cover_image
      end
    end
    resources :authors do
      member do
        delete :destroy_avatar_image
      end
    end
  end

  resources :articles, only: [:show] do
    resources :comments, only: [:create] do
      member do
        post :like
        post :dislike
      end
    end
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "welcome#index"
end

app/models/admin_user.rb
# frozen_string_literal: true

class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
    :registerable,
    :recoverable,
    :rememberable,
    :validatable
end

app/views/layouts/shared/admin_users/_sidebar.html.erb
<aside class="admin-nav" id="adminMenu">
      <div class="row row-menu-button">
        <%= link_to destroy_admin_user_session_path, data: { turbo_method: :delete }, class: "logout" do %>
          <%= image_tag "icons/white/exit.svg", alt: "exit" %>
        <% end %>
        <a href="#" id="adminMenuButton">
          <%= image_tag "icons/white/menu.svg", alt: "menu" %>
        </a>
      </div>
      <div class="row center">
        <%= link_to admin_path, class: "logo" do %>
          <%= image_tag "logo.svg", alt: "Logo Ruby Blog" %>
        <% end %>
      </div>
      <div class="row center column">
        <h3 class="user-name"><%= current_admin_user.name %></h3>
        <h4 class="user-email"><%= current_admin_user.email %></h4>
      </div>
      <div class="row">
        <nav class="menu">
          <%= link_to admin_articles_path, class: current_page?(admin_articles_path) ? "active" : "" do %>
            <div class="icon">
              <%= image_tag "icons/white/posts.svg", alt: "posts" %>
            </div>
            <label for="#">Posts</label>
          <% end %>
          <%= link_to admin_categories_path, class: current_page?(admin_categories_path) ? "active" : "" do %>
            <div class="icon">
              <%= image_tag "icons/white/categories.svg", alt: "categories" %>
            </div>
            <label for="#">Categorias</label>
          <% end %>
          <%= link_to admin_authors_path, class: current_page?(admin_authors_path) ? "active" : "" do %>
            <div class="icon">
              <%= image_tag "icons/white/author.svg", alt: "authors" %>
            </div>
            <label for="#">Autores</label>
          <% end %>
        </nav>
      </div>
    </aside>