config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  devise_for :admin_users

  namespace :admin do
    get "authors/index"
    get "/" => "dashboards#index"
    resources :articles do
      member do
        delete :destroy_cover_image
      end
    end
    resources :categories do
      member do
        delete :destroy_cover_image
      end
    end
    resources :authors do
      member do
        delete :destroy_avatar_image
      end
    end
  end

  resources :articles, only: [:show] do
    resources :comments, only: [:create] do
      member do
        post :like
        post :dislike
      end
    end
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "welcome#index"
end

app/models/article.rb
# frozen_string_literal: true

class Article < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged

  belongs_to :category
  belongs_to :author

  has_many :comments, dependent: :destroy

  has_one_attached :cover_image do |attachable|
    attachable.variant(:thumb, resize_to_limit: [325, 205])
    attachable.variant(:cover, resize_to_limit: [200, 200])
    attachable.variant(:medium, resize_to_limit: [850, 650])
  end
end

app/controllers/admin/articles_controller.rb
# frozen_string_literal: true

module Admin
  class ArticlesController < AdminController
    before_action :set_article, only: [:show, :edit, :update, :destroy, :destroy_cover_image]
    before_action :set_categories, only: [:new, :edit, :show]
    before_action :set_authors, only: [:new, :edit, :show]

    # GET /articles or /articles.json
    def index
      @articles = Article.all.includes(:category)
    end

    # GET /articles/1 or /articles/1.json
    def show
    end

    # GET /articles/new
    def new
      @article = Article.new
    end

    # GET /articles/1/edit
    def edit
    end

    # POST /articles or /articles.json
    def create
      @article = Article.new(article_params)
      @article.cover_image.attach(params[:article][:cover_image])

      respond_to do |format|
        if @article.save
          format.html { redirect_to(admin_article_path(@article), notice: t("controllers.admin.articles.create")) }
          format.json { render(:show, status: :created, location: admin_article_path(@article)) }
        else
          format.html { render(:new, status: :unprocessable_entity) }
          format.json { render(json: @article.errors, status: :unprocessable_entity) }
        end
      end
    end

    # PATCH/PUT /articles/1 or /articles/1.json
    def update
      respond_to do |format|
        if @article.update(article_params)
          format.html { redirect_to(admin_article_path(@article), notice: t("controllers.admin.articles.update"), status: :see_other) }
          format.json { render(:show, status: :ok, location: admin_article_path(@article)) }
        else
          format.html { render(:edit, status: :unprocessable_entity) }
          format.json { render(json: @article.errors, status: :unprocessable_entity) }
        end
      end
    end

    # DELETE /articles/1 or /articles/1.json
    def destroy
      @article.destroy!

      respond_to do |format|
        format.html { redirect_to(admin_articles_path, notice: t("controllers.admin.articles.destroy"), status: :see_other) }
        format.json { head(:no_content) }
      end
    end

    def destroy_cover_image
      @article.cover_image.purge
      respond_to do |format|
        format.turbo_stream { render(turbo_stream: turbo_stream.remove(@article)) }
      end
    end

    private

    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.friendly.find(params.expect(:id))
    end

    def set_categories
      @categories = Category.all
    end

    def set_authors
      @authors = Author.all
    end

    # Only allow a list of trusted parameters through.
    def article_params
      params.require(:article).permit(:title, :body, :cover_image, :category_id, :author_id)
    end
  end
end

app/controllers/articles_controller.rb
# frozen_string_literal: true

class ArticlesController < PublicController
  before_action :set_article, only: [:show]

  def show
    @other_articles = Article.includes(:author, :category, comments: :user)
      .with_attached_cover_image
      .where.not(id: @article.id)
      .order(updated_at: :desc)
      .limit(3)
    @comments = comments_sorted_by
  end

  private

  def set_article
    @article = Article.includes(:author, :category, comments: :user)
      .with_attached_cover_image
      .friendly.find(params.expect(:id))
  end

  def comments_sorted_by
    if params[:sort_by] == "last_comments"
      @article.comments.order(created_at: :asc)
    else
      @article.comments.order(created_at: :desc)
    end
  end

  def article_params
    params.require(:article).permit(:title, :body, :cover_image, :category_id)
  end
end

app/helpers/article_helper.rb
# frozen_string_literal: true

module ArticleHelper
  def markdown(text)
    sanitize(Markdown.new(text).to_html)
  end
end

app/views/admin/articles/_article.html.erb
<div id="<%= dom_id article %>">
  <tr>
    <td><%= l(article.created_at, format: :only_date) %></td>
    <td><%= article.category&.name || "Sem categoria" %></td>
    <td><%= article.title %></td>
    <td>
      <div class="icons">
        <%= link_to admin_article_path(article), title: "Visualizar", alt: "eye" do %>
          <%= image_tag "icons/gray/eye.svg"%>
        <% end %>
  
        <%= link_to edit_admin_article_path(article), alt: "edit" do %>
          <%= image_tag "icons/gray/edit.svg" %>
        <% end %>

        <%= button_to [:admin, article], method: :delete, data: { turbo: "false" }, alt: "close", class: "button clean" do %>
          <%= image_tag "icons/gray/close.svg" %>
        <% end %>
        
      </div>
    </td>
  </tr>
</div>

app/views/admin/articles/_form.html.erb
<div class="row">
  <%= form_with(model: [:admin, article], class: "form", id: "article-form") do |form| %>
      <div class="input-row">
        <div class="input-container">
          <%= form.label :title, class: "label" %>
          <%= form.text_field :title, placeholder: "Digite aqui o título do post", class: "input", disabled: params[:action] == "show" %>
        </div>
      </div>
      <div class="input-row">
        <div class="input-container">
          <%= form.label :body, class: "label" %>
          <%= link_to "[markdown]", "#", id: "markdown-button" if params[:action] != "show" %>
          <%= form.textarea :body, rows: 18, placeholder: "Digite aqui o conteúdo do post", class: "textarea", disabled: params[:action] == "show" %>
        </div>
      </div>

      <div class="input-row">
        <div class="input-container">
          <%= form.label :category_id, class: "label" %>
          <%= form.select :category_id, options_from_collection_for_select(@categories, "id", "name", article.category_id), { include_blank: "Selecione uma categoria" }, {class: "select", disabled: params[:action] == "show"} %>
        </div>
      </div>

      <div class="input-row">
        <div class="input-container">
          <%= form.label :author_id, class: "label" %>
          <%= form.select :author_id, options_from_collection_for_select(@authors, "id", "name", article.author_id), { include_blank: "Selecione um Autor" }, {class: "select", disabled: params[:action] == "show"} %>
        </div>
      </div>

      <div>
        <%= form.label :cover_image, style: "display: block", class: "label-input-file" %>
        <%= (form.file_field :cover_image, style: "margin-bottom: 8px;" ) if params[:action] != "show" %>
        <div id= <%= dom_id(article) %>>
          <% if article.cover_image.attached? %>
            <div style="display: block; margin-bottom: 8px;">
              <%= image_tag article.cover_image.variant(:thumb), style: "display: block;" %>
            </div>
            <% if params[:action] != "show" %>
              <%= link_to "Remover imagem",destroy_cover_image_admin_article_path(article), style: "display: block;", data: { "turbo-confirm": "Tem certeza que deseja remover a imagem?", "turbo-method": :delete } %>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
    <%= button_to "Apagar artigo", [:admin, @article], method: :delete, class: "button small full", form_class: "full", data: {turbo: false} if params[:action] == "show" %>
    <%= form.submit style: "display: none" %>
  <% end %>
</div>

app/views/admin/articles/edit.html.erb
<% content_for :title, "Editing article" %>

<%= link_to "Editar Artigo", admin_articles_path, class: "admin-title" %>

<div class="main-content">
  <div class="row">
    <h2 class="admin-subtitle">Editar artigo</h2>
    <div class="buttons">
      <a href="#" class="button small", onclick="document.forms['article-form'].submit()">
        <%= image_tag "icons/white/save.svg", alt: "save" %>
        Atualizar artigo
      </a>
    </div>
  </div>
</div>

<%= render "form", article: @article %>

app/views/admin/articles/index.html.erb
<h1 class="admin-title">Artigos</h1>
<div class="main-content">
  <div class="row">
    <h2 class="admin-subtitle">Listagem de artigos</h2>
    <div class="buttons">
      <%= link_to new_admin_article_path, class: "button small" do %>
        <%= image_tag "icons/white/add.svg", alt: "add" %>
        Adicionar novo artigo
      <% end %>
    </div>
  </div>
  <div class="row">
    <table class="table">
      <thead>
        <tr>
          <th>Data</th>
          <th>Categoria</th>
          <th>Nome</th>
          <th>Ações</th>
        </tr>
      </thead>
      <tbody>
        <% @articles.each do |article| %>
          <%= render article, show_view_button: true %>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/admin/articles/new.html.erb
<% content_for :title, "Posts - Cadastro" %>

<%= link_to "Artigos", admin_articles_path, class: "admin-title" %>

<div class="main-content">
  <div class="row">
    <h2 class="admin-subtitle">Cadastro de artigo</h2>
    <div class="buttons">
      <a href="#" class="button small", onclick="document.forms['article-form'].submit()">
        <%= image_tag "icons/white/save.svg", alt: "save" %>
        Salvar artigo
      </a>
    </div>
  </div>
</div>

<%= render "form", article: @article %>

app/views/admin/articles/show.html.erb
<%= link_to "Artigos", admin_articles_path, class: "admin-title" %>

<div class="main-content">
  <div class="row">
    <h2 class="admin-subtitle">Visualizar artigo</h2>
  </div>
    <div class="buttons">
      <%= link_to edit_admin_article_path(@article), class: "button small" do %>
        <%= image_tag "icons/white/edit.svg", alt: "edit" %>
        Editar artigo
      <% end %>
    </div>
</div>

<%= render "form", article: @article%>