config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  devise_for :admin_users

  namespace :admin do
    get "authors/index"
    get "/" => "dashboards#index"
    resources :articles do
      member do
        delete :destroy_cover_image
      end
    end
    resources :categories do
      member do
        delete :destroy_cover_image
      end
    end
    resources :authors do
      member do
        delete :destroy_avatar_image
      end
    end
  end

  resources :articles, only: [:show] do
    resources :comments, only: [:create] do
      member do
        post :like
        post :dislike
      end
    end
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "welcome#index"
end

app/models/article.rb
# frozen_string_literal: true

class Article < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged

  belongs_to :category
  belongs_to :author

  has_many :comments, dependent: :destroy

  has_one_attached :cover_image do |attachable|
    attachable.variant(:thumb, resize_to_limit: [325, 205])
    attachable.variant(:cover, resize_to_limit: [200, 200])
    attachable.variant(:medium, resize_to_limit: [850, 650])
  end
end

app/controllers/admin/articles_controller.rb
# frozen_string_literal: true

module Admin
  class ArticlesController < AdminController
    before_action :set_article, only: [:show, :edit, :update, :destroy, :destroy_cover_image]
    before_action :set_categories, only: [:new, :edit, :show]
    before_action :set_authors, only: [:new, :edit, :show]

    # GET /articles or /articles.json
    def index
      @articles = Article.all.includes(:category)
    end

    # GET /articles/1 or /articles/1.json
    def show
    end

    # GET /articles/new
    def new
      @article = Article.new
    end

    # GET /articles/1/edit
    def edit
    end

    # POST /articles or /articles.json
    def create
      @article = Article.new(article_params)
      @article.cover_image.attach(params[:article][:cover_image])

      respond_to do |format|
        if @article.save
          format.html { redirect_to(admin_article_path(@article), notice: t("controllers.admin.articles.create")) }
          format.json { render(:show, status: :created, location: admin_article_path(@article)) }
        else
          format.html { render(:new, status: :unprocessable_entity) }
          format.json { render(json: @article.errors, status: :unprocessable_entity) }
        end
      end
    end

    # PATCH/PUT /articles/1 or /articles/1.json
    def update
      respond_to do |format|
        if @article.update(article_params)
          format.html { redirect_to(admin_article_path(@article), notice: t("controllers.admin.articles.update"), status: :see_other) }
          format.json { render(:show, status: :ok, location: admin_article_path(@article)) }
        else
          format.html { render(:edit, status: :unprocessable_entity) }
          format.json { render(json: @article.errors, status: :unprocessable_entity) }
        end
      end
    end

    # DELETE /articles/1 or /articles/1.json
    def destroy
      @article.destroy!

      respond_to do |format|
        format.html { redirect_to(admin_articles_path, notice: t("controllers.admin.articles.destroy"), status: :see_other) }
        format.json { head(:no_content) }
      end
    end

    def destroy_cover_image
      @article.cover_image.purge
      respond_to do |format|
        format.turbo_stream { render(turbo_stream: turbo_stream.remove(@article)) }
      end
    end

    private

    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.friendly.find(params.expect(:id))
    end

    def set_categories
      @categories = Category.all
    end

    def set_authors
      @authors = Author.all
    end

    # Only allow a list of trusted parameters through.
    def article_params
      params.require(:article).permit(:title, :body, :cover_image, :category_id, :author_id)
    end
  end
end

app/controllers/articles_controller.rb
# frozen_string_literal: true

class ArticlesController < PublicController
  before_action :set_article, only: [:show]

  def show
    @other_articles = Article.includes(:author, :category, comments: :user)
      .with_attached_cover_image
      .where.not(id: @article.id)
      .order(updated_at: :desc)
      .limit(3)
    @comments = comments_sorted_by
  end

  private

  def set_article
    @article = Article.includes(:author, :category, comments: :user)
      .with_attached_cover_image
      .friendly.find(params.expect(:id))
  end

  def comments_sorted_by
    if params[:sort_by] == "last_comments"
      @article.comments.order(created_at: :asc)
    else
      @article.comments.order(created_at: :desc)
    end
  end

  def article_params
    params.require(:article).permit(:title, :body, :cover_image, :category_id)
  end
end

app/helpers/article_helper.rb
# frozen_string_literal: true

module ArticleHelper
  def markdown(text)
    sanitize(Markdown.new(text).to_html)
  end
end

app/views/articles/show.html.erb
<section class="section posts-detail-title-section">
  <div class="container">
    <h1 class="post-detail-title"><%= @article.title %></h1>
  </div>
</section>

<section class="section post-detail-default-section post-detail-image-section">
  <div class="container">
    <div class="primary-content">
      <div class="post-detail-image">
        <%= image_tag(cover_image_fallback(@article, :medium) , alt: @article.title) %>
      </div>
    </div>
    <div class="secondary-content">
      <a href="#" class="post-detail-image-ad">
        <%= image_tag "ad/image-ad.jpg" %>
      </a>
      <div class="share-post">
        <div class="share-post-title">Compartilhar post</div>
        <div class="socials">
          <%= link_to "https://www.facebook.com/sharer/sharer.php?u=#{article_url(@article)}" do %>
            <%= image_tag "icons/gray/facebook.svg" %>
          <% end %>
          <%= link_to "https://twitter.com/intent/tweet?text=#{@article.title}&url=#{article_url(@article)}" do %>
            <%= image_tag "icons/gray/twitter.svg" %>
          <% end %>

          <%= link_to article_url(@article, format: :pdf), target: "_blank" do %>
            PDF
          <% end %>
        </div>
      </div>
    </div>
  </div>
</section>

<section class="section post-detail-default-section author-section">
  <div class="container">
    <div class="primary-content">
      <div class="author">
        <div class="image-container">
          <%= image_tag(avatar_image_fallback(@article.author) , alt: @article.author.name) %>
        </div>
        <div class="text-container">
          <div class="label">Autor</div>
          <div class="description"><%= @article.author.name %></div>
        </div>
      </div>
      <div class="category text-container">
        <div class="label">Categoria</div>
        <div class="description"><%= @article.category.name %></div>
      </div>
      <div class="comments text-container">
        <div class="label">Comentários</div>
        <div class="description">15</div>
      </div>
    </div>
  </div>
</section>


<section class="section post-detail-default-section post-content-section">
  <div class="container">
    <div class="primary-content">
      <div class="post-detail-content">
        <%= markdown(@article.body) %>
      </div>
      <div class="post-detail-author-bio">
        <div class="image">
          <%= image_tag(avatar_image_fallback(@article.author) , alt: @article.author.name) %>
          <div class="text-mobile">
            <div class="label">sobre o autor</div>
            <div class="author-name"><%= @article.author.name %></div>
          </div>
        </div>
        <div class="text">
          <div class="label">sobre o autor</div>
          <div class="author-name"><%= @article.author.name %></div>
          <div class="author-description">
            <%= @article.author.description %>
          </div>
          <div class="author-social">
            <%= link_to @article.author.facebook_profile_url do %>
              <%= image_tag "icons/gray/facebook.svg" %>
            <% end %>

            <%= link_to @article.author.instagram_profile_url do %>
              <%= image_tag "icons/gray/instagram.svg" %>
            <% end %>

            <%= link_to @article.author.twitter_profile_url do %>
              <%= image_tag "icons/gray/twitter.svg" %>
            <% end %>

            <%= link_to @article.author.linkedin_profile_url do %>
              <%= image_tag "icons/gray/linkedin.svg" %>
            <% end %>

            <%= link_to @article.author.youtube_profile_url do %>
              <%= image_tag "icons/gray/youtube.svg" %>
            <% end %>
          </div>
        </div>
      </div>
      <div class="post-detail-comment">
        <div class="comment-title-container">
          <div class="comment-title">Comentários</div>
          <div class="comment-actions">
            <div class="label">ordenar por: </div>
            <%= form_with(url: article_url(@article), method: :get) do |form| %>
              <%= form.select :sort_by, options_for_select([["Últimos comentários", "last_comments"], ["Mais recentes", "more_recents"]], params[:sort_by]), {}, { class:"select clean small", onchange:"this.form.submit()" } %>
            <% end %>
          </div>
        </div>
        <div class="comment-form-container">
          <%= form_with(model: [@article, @article.comments.build], url: article_comments_path(@article), data: { turbo: false }) do |form| %>
            <%= form.text_area :body, class:"textarea darker full double-padding", placeholder:"Insira seu comentário aqui..." %>
            <%= form.submit "Publicar", class:"button small" %>
          <% end %>
        </div>
        <div class="post-detail-comments-list">
          <% @comments.each do |comment| %>
            <% next if comment.new_record? %>

            <div class="post-detail-comment-item">
              <div class="author-row">
                <div>
                  <div class="avatar">
                    <%= image_tag "avatar/man-1.svg" %>
                  </div>
                  <div class="name"><%= comment.user.email.split("@").first %></div>
                </div>
                <div>
                  <div class="date"><%= time_ago_in_words(comment.created_at) %></div>
                </div>
              </div>
              <div class="description-row">
                <p>
                  <%= comment.body %>
                </p>
              </div>
              <div class="actions-row">
                <%= button_to like_article_comment_path(@article, comment), class:"like", form: { turbo: false } do %>
                  <%= comment.like %>
                <% end %>

                <%= button_to dislike_article_comment_path(@article, comment), class:"deslike", form: { turbo: false } do %>
                  <%= comment.dislike %>
                <% end %>

                <%= link_to "", "https://twitter.com/intent/tweet?text=#{comment.body}&url=#{article_url(@article)}", class:"share" %>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
    <div class="secondary-content">
      <a href="#" class="post-content-ad">
        <%= image_tag "ad/post-content-ad.jpg" %>
      </a>
      <div class="post-detail-other-posts">
        <div class="other-posts-title">Outras publicações</div>
        <% @other_articles.each do |other_article| %>
          <a href="#" class="post-resume">
            <%= image_tag(cover_image_fallback(other_article) , alt: other_article.title, class:"post-resume-image") %>
            <h4 class="post-resume-title"><%= other_article.title %></h4>
          </a>
        <% end %>
      </div>
      <a href="#" class="post-content-ad">
        <%= image_tag "ad/post-content-footer-ad.jpg" %>
      </a>
    </div>
  </div>
  </div>
</section>